spring:
  datasource:
    platform: h2
    schema: classpath:schema.sql
    data: classpath:data.sql


  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true

